### ISSUE TITLE
Found few emaill addresses that does not pass the test

### ISSUE THREAD

**Issue by TommiPrami** [Xor-el/EmailValidationPascal#2]
admin@mailserver1
example@localhost
user@localserver
user@tt

Source : https://en.wikipedia.org/wiki/Email_address

(This might be my fault, Top level domains right??)

**Comment by Xor-el** [comment]
thanks for your observations.
those mails at least "admin@mailserver1" should work although am currently away from my development PC to confirm. 
will review it when I have some time. 
Regards.

**Comment by TommiPrami** [comment]
My bad...

User error :)

Sorry 'bout that...

-Tee-
