### ISSUE TITLE
Latest update fails on two of our test cases passed with previous

### ISSUE THREAD

**Issue by TommiPrami** [Xor-el/EmailValidationPascal#3]
email@123.123.123.123
abc."defghi".xyz@example.com

is that indended?

**Comment by Xor-el** [comment]
Thanks for the information.
Just noticed this issue and have contacted the author of the parent version of this library.
Will relate his response to you once he replies. 
Regards.

**Comment by Xor-el** [comment]
@mWaltari, quoting him @jstedfast 
"Yes.
In order to use an IPv4 domain, you need to do it like this: email@[123.123.123.123]

abc."defghi".xyz@domain is also illegal - the local-part must be either a dot-atom string -or- a quoted-string, but not a mix of both. "

Regards.
